### ISSUE TITLE
soluzioni-proposte

### ISSUE THREAD

**Issue by FoxySeta** [csunibo/linguaggi-di-programmazione#15]
@ali-benny ho guardato oggi alle tre soluzioni proposte e hanno diversi errori (in praticamente tutti gli es non saltati). Correggerli uno a uno ci si mette davvero tanto. Io le boccerei aspettando che Andreea e Fede cambino idea e pubblichino le loro.
# 2014-05-23
## 1
Nel passaggio per nome, i parametri non vengono valutati al momento della chiamata. Quindi y non ha valore 51 (ha "valore" x++ e viene valutato ad ogni uso). Al momento dell'assegnamento di z, x++ restituisce il valore ancora non incrementato di x, e quindi z (=x) vale 59. Al secondo assegnamento di z, si riscrive l'istruzione come "x = x + x++" e quindi il valore ottenuto è 118 in entrambe le stampe.
## 2
Memoria statica e heap. La pila non serve poiche', essendo tutte le funzioni o non risorsive o ricorsive in coda, necessintano al più di un solo RdA, che possiamo quindi tenere in memoria statica.
## 3
Una delle possibili spiegazioni è la seguente: l'implementazione che produce l'errore valuta l'&& della condizione del ciclo in modo zelante, quella che non lo produce in modo pigro.
## 4
In scope statico, la prima stampa e la terza stampa non possono dare 25: quella variabile non è sintatticamente visibile da g.
In scope statico, la terza stampa non può dare 55 e 55, perche' le due variabili che hanno quei valori non sono sintatticamente visibili da g.
## 5
Le vtable non sono mai collegate fra di loro. L'oggetto creato deve contenere i campi anche delle classi base al proprio interno. Le vtable non possono contenere campi, le vtable devono contenere anche i metodi delle loro classi base.
## 7
Quello mostrato è un monitor, non una catena statica.
# 2017-05-17
## 2
L'assegnamento di 40 a x fa riferimento alla x della prima chiamata di foo, ma questa viene sempre oscurata dalla x della seconda chiamata di foo.
## 4
Nelle vtable l'ordine è rilevante, e seguire quello delle dichiarazioni passo passo in questo caso è sbagliato. pippo non ha un puntatore alla vtable di A solo perche' e' un rifeimrento di tipo a. w è un intero, non un puntatore. ogg non ha un solo campo x, ma anche tutti i campi ereditati. Essendoci dispatch dinamico, la f invocata è quella di B, non di A. Essendo pippo un riferimento di tipo A, la x in questione è quella di A, non di C. Quindi la somma è 1 + 10 = 11, e non -3 + 100 = 97.
## 5
No! case indica una union. Matricola e codice fiscale non possono convivere in memoria.
# 2018-12-12
## 1
alla i globale (quella a cui si fa riferimento con il suo stesso nome in fie) non viene assegnato 6, bensì 5: x++ è un'operazione di post-incremento, non pre-incremento. E' la y del blocco finale che diventa sei per via del suddetto incremento.
## 1
La prima invocazione a stampa non può vedere la x incrementata, perche' c'e scope statico: stampa quella nel blocco principale. Idem per la seconda stampa, ma l'incremento delle suddette variabili è uno solo.
## 3
Allineamento a parola di 32 bit NON significa "aggiungi 32 bit dopo ogni variabile incorporata". Le dimensioni dei campi di una union non si sommano.
## 4
Ogni oggetto nell'heap contiene un contatore al numero dei riferimenti che puntano ad esso. Questo viene aggiornato in modo incrementale. Quando scende a 0, l'oggetto è distrutto.
## 6
F lancia una X, e quindi il gestore di g anticipa il gestore del main. Quindi anziche' "in main" viene stampato "in g".

**Comment by FoxySeta** [comment]
bump @ali-benny

**Comment by ali-benny** [comment]
Sisi ma le ho postate solo perchè me l'hanno chiesto non perchè erano "corrette"

**Comment by FoxySeta** [comment]
Le togliamo o le lasciamo (scegli tu obv)? Perche' secondo me avere soluzioni e' utile ma solo se sono piu' le cose corrette che le sbagliate.

**Comment by FoxySeta** [comment]
No nessun problema le lascio comunque: le ho solo rinominate come non corrette.
