### ISSUE TITLE
Emoji non supportate

### ISSUE THREAD

**Issue by FoxySeta** [csunibo/linguaggi-di-programmazione#20]
@ali-benny Le domande nuove dell'orale fanno fallire la compilazione in pdf: il motivo e' che al momento per scelta non supportiamo le emoji (oltre stonare con l'estetica di tex se cambiassimo motore di tex per supportarle dovremmo usare xelatex che darebbe un sacco di altri problemi). In generale, e' sempre bene controllare se le proprie modifiche passino i test o no.

**Comment by FoxySeta** [comment]
Visto le piccole dimensioni del problema, sistemato direttamente in "main" con [78e8df2](https://github.com/csunibo/linguaggi-di-programmazione/commit/78e8df2022c8cb53b9b4d589b9d634b64097e8fa)

**Comment by ali-benny** [comment]
Scusami @FoxySeta ma sono stati giorni in cui non sono mai stata a casa, cmq non capisco la scelta di non supportarle, il file era in md e non si usava tex, quindi davvero non capisco il motivo. In ogni caso np, magari scriverlo nella guida. 
Forse potrà essere un problema dato che nei notion vengono utilizzate spesso le emoji

**Comment by FoxySeta** [comment]
Ma tranq non c'è nessunissima fretta in realtà. Per compilare i md in pdf, facciamo comunque usare a pandoc un motore latex, e per semplicità usiamo pdflatex. Xelatex in effetti supporta le emoji, ma usarlo porterebbe dentro diversi problemi per la compatibilità e la manutenzione.

I notionari passati al momento hanno rimosso le emoji prima di spostare lavoro vecchio su csunibo, e hanno evitato di usarle per i lavori sviluppati direttamente su csunibo (l'estetica delle emoji in ogni caso non si sposa con quella dei pdf stile-tex).

Appoggio l'idea di aggiungere al README un avvertimento. Puoi chiedere prima sul gruppo conferma del fatto che vogliamo continuare a non usare le emoji? Magari si trova qualcuno che invece ha voglia di implementarne il supporto.

**Comment by ali-benny** [comment]
Okkks chiedo 😄
